Better diagnositics and setup

diff --git a/glue/bin/run-egmde b/glue/bin/run-egmde
--- a/glue/bin/run-egmde
+++ b/glue/bin/run-egmde
@@ -4,7 +4,15 @@ set -e
 if [ $(id -u) != 0 ] && [ ! -v DISPLAY ] && [ ! -e $SNAP_COMMON/login-session-control.connected ]; then
   echo "ERROR: You need one of: root, a DISPLAY, or to connect the login-session-control interface."
   echo ""
-  echo "To connect the login-session-control interface and add to the login menu:"
+  echo "To connect the login-session-control and desktop-launch interfaces and add to the login menu:"
+  echo "  /snap/egmde-confined-desktop/current/bin/setup.sh"
+  exit 1
+fi
+
+if [ ! -e $SNAP_COMMON/desktop-launch.connected ]; then
+  echo "ERROR: You need to connect the desktop-launch interface."
+  echo ""
+  echo "To connect the login-session-control and desktop-launch interfaces and add to the login menu:"
   echo "  /snap/egmde-confined-desktop/current/bin/setup.sh"
   exit 1
 fi
